export const brands = [
  {
    _key: "brand-0",
    name: "AG1 (Athletic Greens)",
    category: "Comprehensive Wellness",
    tagline: "75 vitamins, minerals & whole-food ingredients in one daily drink",
    innovation: "All-in-one daily nutrition positioning, subscription model success",
    accent: "green",
  },
  {
    _key: "brand-1",
    name: "Four Sigmatic",
    category: "Mushroom Coffee & Elixirs",
    tagline: "Functional mushrooms meet coffee culture",
    innovation: "Pioneered mushroom coffee category, making adaptogens accessible",
    accent: "amber",
  },
  {
    _key: "brand-2",
    name: "Moon Juice",
    category: "Adaptogenic Beauty & Wellness",
    tagline: "Clinical-level adaptogens for modern stress",
    innovation: "Beauty-from-within positioning, clinical dosing in elegant packaging",
    accent: "purple",
  },
  {
    _key: "brand-3",
    name: "Onnit",
    category: "Performance Nutrition",
    tagline: "Total Human Optimization",
    innovation: "Nootropic stack formulations (Alpha BRAIN), athlete endorsements",
    accent: "neutral",
  },
  {
    _key: "brand-4",
    name: "Olipop",
    category: "Functional Beverages",
    tagline: "Prebiotic soda supporting digestive health",
    innovation: "Gut health positioning in mainstream soda format, 9g fiber per can",
    accent: "rose",
  },
  {
    _key: "brand-5",
    name: "Liquid I.V.",
    category: "Hydration Multiplier",
    tagline: "Cellular Transport Technology for rapid hydration",
    innovation: "Science-backed hydration ratio, stick pack convenience, cause marketing",
    accent: "teal",
  },
  {
    _key: "brand-6",
    name: "Magic Spoon",
    category: "Better-For-You Cereal",
    tagline: "High-protein, low-carb nostalgia",
    innovation: "Childhood favorite reimagined with keto/protein positioning",
    accent: "amber",
  },
  {
    _key: "brand-7",
    name: "Recess",
    category: "Sparkling Water + Adaptogens",
    tagline: "Calm, cool, collected in a can",
    innovation: "Mood-positioning in functional beverages, Gen Z branding excellence",
    accent: "teal",
  },
  {
    _key: "brand-8",
    name: "Seed",
    category: "Precision Probiotics",
    tagline: "Daily Synbiotic for gut-skin-heart axis",
    innovation: "Clinical research backing, 2-in-1 capsule technology, microbiome science",
    accent: "green",
  },
  {
    _key: "brand-9",
    name: "Ritual",
    category: "Essential Vitamins Reimagined",
    tagline: "Traceable nutrients in delayed-release capsules",
    innovation: "Radical transparency in sourcing, beadlet-in-oil technology, female-first",
    accent: "amber",
  },
  {
    _key: "brand-10",
    name: "Bulletproof",
    category: "Performance Coffee & Fats",
    tagline: "Biohacking meets coffee culture",
    innovation: "Created butter coffee trend, biohacking community building",
    accent: "neutral",
  },
  {
    _key: "brand-11",
    name: "Organifi",
    category: "Superfood Blends",
    tagline: "Green juice without the juicer",
    innovation: "Convenience positioning for green juice, influencer marketing success",
    accent: "green",
  },
  {
    _key: "brand-12",
    name: "Mindful Foods",
    category: "Activated Superfoods",
    tagline: "Australian organic activated nuts, seeds & superfoods",
    innovation: "Activation process for digestibility, premium Australian organic positioning",
    accent: "amber",
  },
  {
    _key: "brand-13",
    name: "LMNT",
    category: "Electrolyte Drink Mix",
    tagline: "Zero sugar electrolytes for low-carb lifestyles",
    innovation: "Keto/paleo positioning, science-backed salt ratios, no sugar/additives",
    accent: "rose",
  },
  {
    _key: "brand-14",
    name: "Huel",
    category: "Complete Nutrition",
    tagline: "Nutritionally complete food in minutes",
    innovation: "Meal replacement for busy lifestyles, sustainability positioning",
    accent: "neutral",
  },
  {
    _key: "brand-15",
    name: "Sakara Life",
    category: "Plant-Based Meal Delivery",
    tagline: "Organic, plant-rich nutrition programs",
    innovation: "Luxury wellness meal delivery, celebrity following, beauty nutrition",
    accent: "rose",
  },
];
